env:
  global:
    - secure: XXMv0vRsDTrTrveNpapr+DxwgpIz5etayWsoLrRKEPIkZ6bWJFNL6MLDXSCjQE9zHk3PgKKpFP1QStAq/IWxEs0GF6C1+tkkja6rZdgI+r/kxR17G1P5/pQiVTF96nxufGSjj5XqaulUUrgzc4pw+mrGX5oyLDpjE4jxWvxUu3lnMGufJlA5P3ZW9aK7TL78GUH0Lacn96HquYPCEX6HvLhI/f20QcWkH5hsFa9c1jX50pqHGPAITHm+mw13ndYQgEqF2a3zpJvyi/Z1nqVOrdeIqVYr3UANGbrWDoTtXkX6XJruA6FUohCOYyHCG++6frR1GDk5jRk4ivLE44s9er8kBirg0JA9D8Hlamk9FApiuUyF283OLugao4CNoGh1Za/kZUBoTtcjn0AC9ML8drVhvnJKDLD3iLwwZptzZh2WKRoHKtvHpAK5tKM44AfZYUPUhB149rO8UG2YqSGgwgIwymTenQeFbOsAPpjuMJ1CPx2XlwitS69CS19AI9WKHUiC4g3zWEVTv316ylUfvGUv5dZxXKUNFLQP3qwRMMU4fD/CRuQVFqDg+5uv6TpuvH6N8u073CLwRlhyR+8B/Y01RZXYhpZtk9TsqdMD2TUT1asphG9sjCYQL8KxwRMK9qSoNs/70byhxJbei3FnTfEdx6tHx/3VDjHx3O9t23A=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/KADhosts_git_azet12
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
