env:
  global:
    - secure: QvzBSxt4S2Y2DW4Dm/QqN6yaVGzx3UcmrGE41EgsFqowbSuZSs0b9Ift5P18kp0APNQiQlF2XDefs2XOHgPsBYeEY6ufd4ZpO/ksJwk+m54uSwSMv8gpSim2Y7+K56Yac+7UALtlcK7NF5LouEJX+i5SXWulGZHgu/9nd0WktRWIOQs6e7Y61YaEHynuZlCIz/yLgqQGVBlLRgrtWFeBUj7vTTVdXKbo/0O5V+X769I9mRzpFKSnG5z/We2iA0f5bEbmyULv9URLaaPoMUL5cfeYfZTK8H1fx3NR508C4gGn/o0bmC66hkSHrPe05wmigOxDnLStyIt0+6vmzQEZj2/W6lrZCBtnslUjcvEqBPf3B5AWHiAd+A+G0zMHDdM1zy8ed6d7KSXO0eS1LM8A0WsUZr3g9J4EzvcZ/82RmjI5loPzppNPHB5NFhDlcNjWsE2Wcll2Y461aMkj0TY+j4QhEwxJv3OrH4Fdf8lIzHBQpwvPQ7SiifZN+KRZ+TodsxBesqeKfpjfm9aRSIjgQ7cq0GnP3VICXmYX7tl48yCuPKLeT0GBh6plO8LhFcMrXb9lD6T7thNdJOlg+OTNRSzs8GJigATXhPpqvFmMIkuMNr21YZduXdoUxf9RHEa/RnZStjEn/nZfnLGUUusRX3hAy1tFnFGFmYT1udytdiw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/KADhosts_git_azet12
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
