env:
  global:
    - secure: SSRZXJrd3AENhVYgiMJlt0gTktKQVsEAE4hEOmOFFJMymhHcKBQuRX1HPdtrXLzUKHzI97SN8Nm11q7uOSCMAIQ96zDSeFdrCYjsTBCMSifi04y6bHw3VqkonVz76AiODbwmCWhlEZYoq2RvQd9Nkd7RpEgSbaSGxn5lHHDjaZ6DAXSn4stfsMtI36a6gJ0alFVd1jl136BiT8vBs7SfQ56wGqcwafnyTTT1bfLj1xR2Lc8IAepoHOkeggnf6YBsXVyCb0s+ys3iPC+Jd6oTQTE6TO2slKNK1TrnRQi5CuQFwbkjfL+nCpDH2POnn3ARkPWYLLa4lXBkSmTlPwZU8z/JZ+vgpb8F2kWOVMKxmOP9JFSqxfzwnCp3jupmE3J7ks1iqIkbpExAC+QEpOLSvZVjtHs/P5Tt19sC7Gozv2CRMR6/Fb4opwHtZOrIbr5kOjEkkcA0fSZ7tC3jUcyNV8UlDR4Xsgk6G3GT08+Ue+Ql9sbrEFZ33l8RYqch534CGGchZdHIo42Uk8OZwE+4/h7q/QOdJ4l9X4trZu4RdFinREkdgJFag85ejxrYV6i7wv+IwnzhaqOeA0vWKYsa39RY3yaeBMi10Ve42qAuEPgwSEOveRgdgflEtlta0lx1rd1SLYXgXTbitCk//6JfP6Cq+cfCdXulIbeYVMO5Y/M=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/KADhosts_git_azet12
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
