env:
  global:
    - secure: pSrE7faJhzeywqr4so0owU+6sdvd1kw8A5xzz2Uyp/BTbbkQzrkBl/8qV+ud0jLnkJRgyTkQdV+bpt0L/OUW6rQYj1IpnbEL6Vxbe4FOyo0HJtDE/OyvcOBZwPCLkq/ktgRupZGtZtuxBUFrY0cBWwYh3LK8+3964i+vvVj+xLOUczRuHUYAPqVTQhS29XqqFjlBNTr98/Afh4XSBqsdw09gd/GydmotglNGZMARIFYGTkLyOhg93ErtOOTi7oLmGcAF6O3Yj16Le/ahul9vqOP6jqp8pR+R7DXyaqvgbEXJTj+37lZ70GnWsukqFH8XUm/2Q8JCEq0OK1u6YkctQbyLE16ucxBpbRj4kMfdf/fPdZ9ArmMrGo3sSIoUIZh5YLKm8O052arc71EZURWbY6vtAHHB6pEbYY9q0JJf5lClN1puTnB0VMoSTrpe99L95Gct7C7TTBTrdehZgsi/gwi4HS6fbBh8ZviTwhvFbBXYk4f18wDN80PIQzMy+H3E/WfFt35JlxjsJNo32qhEyK+tM9tYZmTxxBxI+xswv+ptZhK7WqwHnsg+K/3FEhEycjJKVBmH+I/VnQxUaWo4YAiHcnjehLEcijbxFKw3BpwkRAy2RgvCoVmy5fa6QMVt4jy+vxYxiypt/tWn+0C9x3/Sv5OyF8aruRI0DiAca5E=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/KADhosts_git_azet12
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
